version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prodhub_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=prodhub_db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    build: .
    command: gunicorn product_importer.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - RDS_DB_NAME=prodhub_db
      - RDS_USERNAME=prodhub_user
      - RDS_PASSWORD=mysecretpassword
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - DEBUG=False
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - shared_uploads:/app/uploads       # ðŸ”¥ Shared volume
    restart: unless-stopped

  worker:
    build: .
    command: celery -A product_importer worker --loglevel=info
    environment:
      - RDS_DB_NAME=prodhub_db
      - RDS_USERNAME=prodhub_user
      - RDS_PASSWORD=mysecretpassword
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - DEBUG=False
    depends_on:
      - db
      - redis
    volumes:
      - shared_uploads:/app/uploads       # ðŸ”¥ Same shared volume as web

volumes:
  postgres_data:
  static_volume:
  shared_uploads:                         # ðŸ”¥ New shared uploads volume
